### ISSUE TITLE
article_<緊急連絡先>

### ISSUE THREAD

**Issue by ayuayu17** [AyaExpTech/FY23-OmiyaFW#10]
### あなたが追加したい記事のタイトルはなんですか？

緊急連絡先

### そのページは他のページとどのような関係を持ちますか?

ホーム >緊急連絡先

### あなたが追加したい記事はどのような内容ですか？

緊急時に連絡をする用の大串さんの電話番号

### あなたが追加したい記事の本文を記入してください。

緊急連絡先(大串さん)
XXX-XXXX-XXXX

**Comment by AyaExpTech** [comment]
電話番号が思いっきり個人情報なのでとりあえず伏せ字にしておきました

**Comment by AyaExpTech** [comment]
本人曰く社用携帯で名刺とかにも書いているような番号とのこと。  
セキュリティ対応などはとくになしで問題ない旨の許可を取れたのでそのまま載せます

掲載する電話番号は`080-7852-6650`
