### ISSUE TITLE
bug_アトラクション・イベントページの表示崩れ

### ISSUE THREAD

**Issue by HirotaAi** [AyaExpTech/FY23-OmiyaFW#42]
### あなたが不具合だと感じている事象は何ですか？

アトラクション＆イベント全体的な表示崩れ

### その事象を再現するために、どのような手順をとれば良いと考えられますか？

- 該当箇所の修正

### その事象が起こっている部分は、本来どのように動くべきだと考えていますか？

ページが正しく表示されている状態

### その事象はどの端末で発生しましたか？

Macbook Air

### その事象はどのブラウザで発生しましたか？

Google Chrome

### その事象はどのOSで発生しましたか？

macOS Big Sur バージョン 11.3.1

### 補足があればここに書いてください。

おつ

**Comment by AyaExpTech** [comment]
正しいMarkdownを書かないとこういう事が起こるのだ
