### ISSUE TITLE
bug_アクセス目次のルート2,3へのリンクが正常でない

### ISSUE THREAD

**Issue by ayuayu17** [AyaExpTech/FY23-OmiyaFW#44]
### あなたが不具合だと感じている事象は何ですか？

アクセスのページのルート2,3へのショートカットが動かない(ルート1は動く)

### その事象を再現するために、どのような手順をとれば良いと考えられますか？

ワカラナイデス...

### その事象が起こっている部分は、本来どのように動くべきだと考えていますか？

ちゃんと下に動いて欲しい...

### その事象はどの端末で発生しましたか？

恐らく全端末

### その事象はどのブラウザで発生しましたか？

Google Chrome

### その事象はどのOSで発生しましたか？

恐らく全て

**Comment by AyaExpTech** [comment]
パスの指定がおかしいことになっていますね
