### ISSUE TITLE
bug_一部表示崩れ

### ISSUE THREAD

**Issue by yuri-matsuzaki** [AyaExpTech/FY23-OmiyaFW#51]
### 誤字脱字が存在する場所はどこですか？

[ゴジラ・ザ・ミッション 巨大怪獣迫る危機からの脱出]の説明文と[アトムの月面旅行]の説明文、[レオとライヤのジャングルダンスパーティー]の説明文、[飛べ！ジャングルの勇者レオ]の説明文、以降のアトラクション説明文が左に偏り過ぎている…？

### その部分は本来どのように表示されるべきですか？

[世界最大級 とびっきりスゴい！ジャンボガラポンくじ]の説明文みたいな感じの表示の方が見やすいかも！

**Comment by AyaExpTech** [comment]
たーぶん #42 で治ってません？これ
